<?php
/**
 * AddressApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\BusinessPartner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Business Partner (A2X)
 *
 * This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\BusinessPartner\Test\Api;

use \BeLenka\SAP\BusinessPartner\Configuration;
use \BeLenka\SAP\BusinessPartner\ApiException;
use \BeLenka\SAP\BusinessPartner\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AddressApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\BusinessPartner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AddressApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for aBusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDDelete
     *
     * Deletes business partner address record identified by address ID and business partner number..
     *
     */
    public function testABusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDGet
     *
     * Retrieves business partner address data by using the key field..
     *
     */
    public function testABusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDPatch
     *
     * Updates business partner address data..
     *
     */
    public function testABusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToAddressUsageGet
     *
     * Retrieves address usage linked to business partner address..
     *
     */
    public function testABusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToAddressUsageGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToAddressUsagePost
     *
     * Creates an address usage record linked to a existing business partner address..
     *
     */
    public function testABusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToAddressUsagePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToBPAddrDepdntIntlLocNumberGet
     *
     * Retrieves address dependent data for the business partner address..
     *
     */
    public function testABusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToBPAddrDepdntIntlLocNumberGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToBPIntlAddressVersionGet
     *
     * Get entities from related to_BPIntlAddressVersion.
     *
     */
    public function testABusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToBPIntlAddressVersionGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToBPIntlAddressVersionPost
     *
     * Add new entity to related to_BPIntlAddressVersion.
     *
     */
    public function testABusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToBPIntlAddressVersionPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToEmailAddressGet
     *
     * Retrieves email address data linked to business partner address fields..
     *
     */
    public function testABusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToEmailAddressGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToEmailAddressPost
     *
     * Creates a new email address data for the existing business partner address..
     *
     */
    public function testABusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToEmailAddressPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToFaxNumberGet
     *
     * Retrieves fax address data linked to business partner address..
     *
     */
    public function testABusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToFaxNumberGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToFaxNumberPost
     *
     * Creates a new fax address data for the existing business partner address..
     *
     */
    public function testABusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToFaxNumberPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToMobilePhoneNumberGet
     *
     * Retrieves mobile/telephone address records linked to business partner address..
     *
     */
    public function testABusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToMobilePhoneNumberGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToMobilePhoneNumberPost
     *
     * Creates a new  mobile/telephone address record for the existing business partner address..
     *
     */
    public function testABusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToMobilePhoneNumberPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToPhoneNumberGet
     *
     * Retrieves mobile/telephone address records linked to business partner address..
     *
     */
    public function testABusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToPhoneNumberGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToPhoneNumberPost
     *
     * Creates a new  mobile/telephone address record for the existing business partner address..
     *
     */
    public function testABusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToPhoneNumberPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToURLAddressGet
     *
     * Retrieves home page URL address records linked to business partner address..
     *
     */
    public function testABusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToURLAddressGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToURLAddressPost
     *
     * Creates a new home page URL address record to the existing business partner address..
     *
     */
    public function testABusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToURLAddressPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerAddressGet
     *
     * Retrieves business partner address data..
     *
     */
    public function testABusinessPartnerAddressGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerAddressPost
     *
     * Creates a new address data for an existing business partner..
     *
     */
    public function testABusinessPartnerAddressPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerBusinessPartnerToBusinessPartnerAddressGet
     *
     * Retrieves business partner address data..
     *
     */
    public function testABusinessPartnerBusinessPartnerToBusinessPartnerAddressGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerBusinessPartnerToBusinessPartnerAddressPost
     *
     * Creates a new address data for an existing business partner..
     *
     */
    public function testABusinessPartnerBusinessPartnerToBusinessPartnerAddressPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
