<?php
/**
 * BankApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\BusinessPartner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Business Partner (A2X)
 *
 * This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\BusinessPartner\Test\Api;

use \BeLenka\SAP\BusinessPartner\Configuration;
use \BeLenka\SAP\BusinessPartner\ApiException;
use \BeLenka\SAP\BusinessPartner\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BankApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\BusinessPartner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BankApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationDelete
     *
     * Deletes business partner bank data..
     *
     */
    public function testABusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationGet
     *
     * Retrieves business partner bank data by using key fields..
     *
     */
    public function testABusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationPatch
     *
     * Updates business partner bank data..
     *
     */
    public function testABusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerBankGet
     *
     * Retrieves business partner bank data..
     *
     */
    public function testABusinessPartnerBankGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerBankPost
     *
     * Creates new business partner bank data..
     *
     */
    public function testABusinessPartnerBankPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerBusinessPartnerToBusinessPartnerBankGet
     *
     * Retrieves business partner bank data..
     *
     */
    public function testABusinessPartnerBusinessPartnerToBusinessPartnerBankGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerBusinessPartnerToBusinessPartnerBankPost
     *
     * Creates new business partner bank data..
     *
     */
    public function testABusinessPartnerBusinessPartnerToBusinessPartnerBankPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
