<?php
/**
 * CustomerTextApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\BusinessPartner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Business Partner (A2X)
 *
 * This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\BusinessPartner\Test\Api;

use \BeLenka\SAP\BusinessPartner\Configuration;
use \BeLenka\SAP\BusinessPartner\ApiException;
use \BeLenka\SAP\BusinessPartner\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomerTextApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\BusinessPartner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomerTextApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for aCustomerCustomerToCustomerTextGet
     *
     * Retrieves customer text data..
     *
     */
    public function testACustomerCustomerToCustomerTextGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aCustomerCustomerToCustomerTextPost
     *
     * Creates customer long text..
     *
     */
    public function testACustomerCustomerToCustomerTextPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aCustomerTextCustomerCustomerLanguageLanguageLongTextIDLongTextIDDelete
     *
     * Deletes customer text records by using key fields..
     *
     */
    public function testACustomerTextCustomerCustomerLanguageLanguageLongTextIDLongTextIDDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aCustomerTextCustomerCustomerLanguageLanguageLongTextIDLongTextIDGet
     *
     * Retrieves customer text records using the key fields..
     *
     */
    public function testACustomerTextCustomerCustomerLanguageLanguageLongTextIDLongTextIDGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aCustomerTextCustomerCustomerLanguageLanguageLongTextIDLongTextIDPatch
     *
     * Updates customer text records by using the key fields..
     *
     */
    public function testACustomerTextCustomerCustomerLanguageLanguageLongTextIDLongTextIDPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aCustomerTextGet
     *
     * Retrieves customer text data..
     *
     */
    public function testACustomerTextGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aCustomerTextPost
     *
     * Creates customer long text..
     *
     */
    public function testACustomerTextPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
