<?php
/**
 * HomePageURLApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\BusinessPartner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Business Partner (A2X)
 *
 * This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\BusinessPartner\Test\Api;

use \BeLenka\SAP\BusinessPartner\Configuration;
use \BeLenka\SAP\BusinessPartner\ApiException;
use \BeLenka\SAP\BusinessPartner\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * HomePageURLApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\BusinessPartner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class HomePageURLApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for aAddressHomePageURLAddressIDAddressIDPersonPersonOrdinalNumberOrdinalNumberValidityStartDatedatetimeValidityStartDateIsDefaultURLAddressIsDefaultURLAddressDelete
     *
     * Deletes home page URL address record by key fields..
     *
     */
    public function testAAddressHomePageURLAddressIDAddressIDPersonPersonOrdinalNumberOrdinalNumberValidityStartDatedatetimeValidityStartDateIsDefaultURLAddressIsDefaultURLAddressDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aAddressHomePageURLAddressIDAddressIDPersonPersonOrdinalNumberOrdinalNumberValidityStartDatedatetimeValidityStartDateIsDefaultURLAddressIsDefaultURLAddressGet
     *
     * Retrieves home page URL address records by using key fields..
     *
     */
    public function testAAddressHomePageURLAddressIDAddressIDPersonPersonOrdinalNumberOrdinalNumberValidityStartDatedatetimeValidityStartDateIsDefaultURLAddressIsDefaultURLAddressGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aAddressHomePageURLAddressIDAddressIDPersonPersonOrdinalNumberOrdinalNumberValidityStartDatedatetimeValidityStartDateIsDefaultURLAddressIsDefaultURLAddressPatch
     *
     * Updates home page URL address record by key fields..
     *
     */
    public function testAAddressHomePageURLAddressIDAddressIDPersonPersonOrdinalNumberOrdinalNumberValidityStartDatedatetimeValidityStartDateIsDefaultURLAddressIsDefaultURLAddressPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aAddressHomePageURLGet
     *
     * Retrieves home page URL address records linked to business partner address..
     *
     */
    public function testAAddressHomePageURLGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aAddressHomePageURLPost
     *
     * Creates a new home page URL address record to the existing business partner address..
     *
     */
    public function testAAddressHomePageURLPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBPContactToAddressRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDatedatetimeValidityEndDateAddressIDAddressIDToURLAddressGet
     *
     * Retrieves home page URL address records linked to business partner address..
     *
     */
    public function testABPContactToAddressRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDatedatetimeValidityEndDateAddressIDAddressIDToURLAddressGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBPContactToAddressRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDatedatetimeValidityEndDateAddressIDAddressIDToURLAddressPost
     *
     * Creates a new home page URL address record to the existing business partner address..
     *
     */
    public function testABPContactToAddressRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDatedatetimeValidityEndDateAddressIDAddressIDToURLAddressPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToURLAddressGet
     *
     * Retrieves home page URL address records linked to business partner address..
     *
     */
    public function testABusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToURLAddressGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aBusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToURLAddressPost
     *
     * Creates a new home page URL address record to the existing business partner address..
     *
     */
    public function testABusinessPartnerAddressBusinessPartnerBusinessPartnerAddressIDAddressIDToURLAddressPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
