<?php
/**
 * SupplierCompanyTextApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\BusinessPartner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Business Partner (A2X)
 *
 * This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\BusinessPartner\Test\Api;

use \BeLenka\SAP\BusinessPartner\Configuration;
use \BeLenka\SAP\BusinessPartner\ApiException;
use \BeLenka\SAP\BusinessPartner\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SupplierCompanyTextApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\BusinessPartner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SupplierCompanyTextApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for aSupplierCompanySupplierSupplierCompanyCodeCompanyCodeToCompanyTextGet
     *
     * Retrieves supplier company text data attached to company data..
     *
     */
    public function testASupplierCompanySupplierSupplierCompanyCodeCompanyCodeToCompanyTextGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSupplierCompanySupplierSupplierCompanyCodeCompanyCodeToCompanyTextPost
     *
     * Creates supplier company text data..
     *
     */
    public function testASupplierCompanySupplierSupplierCompanyCodeCompanyCodeToCompanyTextPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSupplierCompanyTextGet
     *
     * Retrieves supplier company text data attached to company data..
     *
     */
    public function testASupplierCompanyTextGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSupplierCompanyTextPost
     *
     * Creates supplier company text data..
     *
     */
    public function testASupplierCompanyTextPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSupplierCompanyTextSupplierSupplierCompanyCodeCompanyCodeLanguageLanguageLongTextIDLongTextIDDelete
     *
     * Deletes supplier company text data..
     *
     */
    public function testASupplierCompanyTextSupplierSupplierCompanyCodeCompanyCodeLanguageLanguageLongTextIDLongTextIDDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSupplierCompanyTextSupplierSupplierCompanyCodeCompanyCodeLanguageLanguageLongTextIDLongTextIDGet
     *
     * Retrieves supplier company text data by using the key fields..
     *
     */
    public function testASupplierCompanyTextSupplierSupplierCompanyCodeCompanyCodeLanguageLanguageLongTextIDLongTextIDGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSupplierCompanyTextSupplierSupplierCompanyCodeCompanyCodeLanguageLanguageLongTextIDLongTextIDPatch
     *
     * Updates supplier company text data..
     *
     */
    public function testASupplierCompanyTextSupplierSupplierCompanyCodeCompanyCodeLanguageLanguageLongTextIDLongTextIDPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
