<?php
/**
 * SupplierCompanyApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\BusinessPartner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Business Partner (A2X)
 *
 * This service enables you to create, display, update, and delete data related to Business Partner, Supplier, and Customer with the data provided in a payload, in an API call. This service also supports create deep entity operation and batch processing.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\BusinessPartner\Test\Api;

use \BeLenka\SAP\BusinessPartner\Configuration;
use \BeLenka\SAP\BusinessPartner\ApiException;
use \BeLenka\SAP\BusinessPartner\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SupplierCompanyApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\BusinessPartner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SupplierCompanyApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for aSupplierCompanyGet
     *
     * Retrieves supplier company data..
     *
     */
    public function testASupplierCompanyGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSupplierCompanyPost
     *
     * Creates supplier company data..
     *
     */
    public function testASupplierCompanyPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSupplierCompanySupplierSupplierCompanyCodeCompanyCodeGet
     *
     * Retrieves supplier company data using key fields..
     *
     */
    public function testASupplierCompanySupplierSupplierCompanyCodeCompanyCodeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSupplierCompanySupplierSupplierCompanyCodeCompanyCodePatch
     *
     * Updates supplier company data using key fields..
     *
     */
    public function testASupplierCompanySupplierSupplierCompanyCodeCompanyCodePatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSupplierCompanySupplierSupplierCompanyCodeCompanyCodeToCompanyTextGet
     *
     * Retrieves supplier company text data attached to company data..
     *
     */
    public function testASupplierCompanySupplierSupplierCompanyCodeCompanyCodeToCompanyTextGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSupplierCompanySupplierSupplierCompanyCodeCompanyCodeToCompanyTextPost
     *
     * Creates supplier company text data..
     *
     */
    public function testASupplierCompanySupplierSupplierCompanyCodeCompanyCodeToCompanyTextPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSupplierCompanySupplierSupplierCompanyCodeCompanyCodeToSupplierDunningGet
     *
     * Retrieves dunning records attached to supplier company data..
     *
     */
    public function testASupplierCompanySupplierSupplierCompanyCodeCompanyCodeToSupplierDunningGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSupplierCompanySupplierSupplierCompanyCodeCompanyCodeToSupplierDunningPost
     *
     * Creates a new dunning records attached to supplier company..
     *
     */
    public function testASupplierCompanySupplierSupplierCompanyCodeCompanyCodeToSupplierDunningPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSupplierCompanySupplierSupplierCompanyCodeCompanyCodeToSupplierGet
     *
     * Retrieves supplier general data..
     *
     */
    public function testASupplierCompanySupplierSupplierCompanyCodeCompanyCodeToSupplierGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSupplierCompanySupplierSupplierCompanyCodeCompanyCodeToSupplierWithHoldingTaxGet
     *
     * Retrieves supplier withholding tax records..
     *
     */
    public function testASupplierCompanySupplierSupplierCompanyCodeCompanyCodeToSupplierWithHoldingTaxGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSupplierCompanySupplierSupplierCompanyCodeCompanyCodeToSupplierWithHoldingTaxPost
     *
     * Creates new supplier witholding tax data..
     *
     */
    public function testASupplierCompanySupplierSupplierCompanyCodeCompanyCodeToSupplierWithHoldingTaxPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSupplierSupplierToSupplierCompanyGet
     *
     * Retrieves supplier company data..
     *
     */
    public function testASupplierSupplierToSupplierCompanyGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSupplierSupplierToSupplierCompanyPost
     *
     * Creates supplier company data..
     *
     */
    public function testASupplierSupplierToSupplierCompanyPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
